# Generated by Django 3.0b1 on 2019-12-03 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Trainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='McqQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('McqQuestionName', models.TextField(default='', max_length=250)),
                ('Choice1', models.CharField(default='', max_length=50)),
                ('Choice2', models.CharField(default='', max_length=50)),
                ('Choice3', models.CharField(default='', max_length=50)),
                ('Choice4', models.CharField(default='', max_length=50)),
                ('CorrectAnswer', models.CharField(choices=[('A', 'Choice1'), ('B', 'Choice2'), ('C', 'Choice3'), ('D', 'Choice4')], max_length=1)),
                ('TopicName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trainer.Topic')),
            ],
            options={
                'db_table': 'mcqQuestion',
            },
        ),
    ]
