# Generated by Django 3.0b1 on 2019-11-28 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrainingCode', models.IntegerField(help_text='please enter number ')),
                ('TrainingName', models.CharField(max_length=150)),
                ('TrainingStartDate', models.DateField()),
                ('TrainingDuration', models.CharField(help_text='6 months', max_length=15)),
                ('picture', models.ImageField(default='default.jpg', upload_to='Training_Pic/')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training',
            },
        ),
    ]
