# Generated by Django 3.0b1 on 2019-11-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovernmentEmployee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='TrainingCode',
            field=models.IntegerField(help_text='please enter a number '),
        ),
    ]
