# Generated by Django 3.0b1 on 2019-11-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MinistryName', models.CharField(max_length=100)),
                ('MinisterName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'ministry',
            },
        ),
    ]
