# Generated by Django 3.0b1 on 2019-11-30 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GovernmentEmployee', '0002_auto_20191128_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerTakenCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GovernmentEmployee.Training')),
                ('TrainerName', models.ForeignKey(limit_choices_to={'is_trainer': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
